language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install mock"
  - "pip install pytest-cov"
  - "pip install -e ."
script: py.test tests/ --cov bankid --cov-report term-missing


