language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
install:
  - "pip install coverage"
  - "pip install -r requirements.txt"
script: nosetests tests --with-coverage --cover-package=bankid

