language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "nightly"
  - pypy
matrix:
  allow_failures:
    - python: 2.6
    - python: "nightly"
    - python: pypy
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install mock"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install -e ."
script: py.test tests/ --cov bankid --cov-report term-missing
after_success:
  - coveralls

