language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install mock"
  - "pip install 'pytest_cov<2.6.0'"
  - "pip install python-coveralls"
  - "pip install -e ."
script: py.test tests/ --cov bankid --cov-report term-missing
after_success:
  - coveralls

